services:
  restaurant-db:
    image: postgres:16
    container_name: restaurant-db
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data

  customer-db:
    image: postgres:16
    container_name: customer-db
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - customer_db_data:/var/lib/postgresql/data

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

  notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data

volumes:
  restaurant_db_data:
  customer_db_data:
  order_db_data:
  payment_db_data:
  notification_db_data: