server.port=9001
spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

restaurant.microservice.url=http://Restaurant-Microservice/restaurant/
payment.microservice.url=http://Payment-Microservice/payment/save
customer.microservice.url=http://Customer-Microservice/customer/

