server.port=9001
spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5435/order_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

restaurant.microservice.url=http://restaurant-service/restaurants/
payment.microservice.url=http://payment-service/payment/save
customer.microservice.url=http://customer-service/customers/
notification.microservice.url=http://notification-service/notifications

